### ISSUE TITLE
Relicense to MPL 2.0

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#100]
Dear contributors (i.e. @Moredread, @killercup, @tilpner and @llogiq),

Would you agree to re-license your contributions to Carboxyl under the [Mozilla Public License Version 2.0](https://www.mozilla.org/en-US/MPL/2.0/)?

To provide some context just in case, anyone of you has not read this: I started [a conversation](https://github.com/reactive-rs/meta/issues/1) about creating a reactive ecosystem based on Carboxyl. During that discussion it turned out that a lot of people consider LGPL problematic to use for Rust code, as it limits usage in proprietary software too much. I have been convinced that my original intention to make proprietary users contribute bug fixes & improvements back upstream is better implemented using MPL 2.0.

Of course, in order to change that, we need to have a consensus among contributors to change the license. Please state your opinion on that, and if you are fine with it, explicitly say: _I hereby consent to make my contributions to Carboxyl available under the Mozilla Public License Version 2.0_

**Comment by tilpner** [comment]
Uhh, that's a one-line `#![feature(...)]` change, but sure. Good choice!

I hereby consent to make my contributions to Carboxyl available under the Mozilla Public License Version 2.0

**Comment by killercup** [comment]
I hereby consent to make my contributions to Carboxyl available under the Mozilla Public License Version 2.0

**Comment by milibopp** [comment]
@tilpner I know… but it does legally make you a contributor, I think.

**Comment by Moredread** [comment]
I hereby consent to make my contributions to Carboxyl available under the Mozilla Public License Version 2.0

**Comment by llogiq** [comment]
I hereby consent to make my contributions to Carboxyl available under the Mozilla Public License Version 2.0

**Comment by Moredread** [comment]
I think that's everyone?

**Comment by milibopp** [comment]
Yeah, if anyone feels inclined to make a PR, go ahead. I'll do it someday. Been busy lately…

**Comment by milibopp** [comment]
Closed by #103.
