### ISSUE TITLE
Comparison to Sodium?

### ISSUE THREAD

**Issue by dakom** [aepsil0n/carboxyl#110]
This library looks very cool! Really exciting to see this possibility :D

How does it differ from Sodium, given the work-in-progress push-pull Rust port? https://github.com/clinuxrulz/sodium-rust-push-pull

**Comment by milibopp** [comment]
Frankly, I do not know. Never seen that library, as it appears to be quite new. Sodium was a huge source of inspiration for me in the development process, so I imagine it could be rather similar.
