### ISSUE TITLE
No weak pointers?

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#47]
[According to @acrichton](http://users.rust-lang.org/t/using-unstable-apis-tell-us-about-it/157/97?u=aepsil0n) weak pointers won't be stabilized for 1.0. Internally this crate makes heavy use of them, so it is unlikely that it will be ready to use for 1.0.

**Ideas to get around this**
- **Shipping own `Weak<T>`:** Would not be exposed, so could be done as a mere implementation detail. Also fairly easy to do (just copy & paste from stdlib).
- **Lifetime bounds instead of ref-counting:** Good for performance, but it might make the library slightly harder to use, as this will propagate into the API. This approach is radically different and goes into afaik unexplored terrain for FRP libraries. Requires some experimentation.

**Comment by milibopp** [comment]
**Shipping own `Weak<T>`** appears to be unfeasible, because the building blocks of the `arc` module are still unstable. See the  out-of-tree implementation on [this branch](https://github.com/aepsil0n/carboxyl/tree/outoftree-arc).

**Comment by jakerr** [comment]
Heads up! rust-lang/rust#27718 just went into **final-comment-period** for stabilizing arc_weak, rc_weak etc.

**Comment by milibopp** [comment]
Oh, that's nice. Thank you for the notification! Looking forward to finally bring carboxyl to stable Rust ;)
