### ISSUE TITLE
Rename Cell to Signal/Behaviour

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#53]
This is a bit of bike-shedding, but the current terminology has some issues:
- It is a bit confusing given the existence of the Rust standard library `Cell` and `RefCell` types
- A `Cell` seems to contain a certain value (also because the first reason), which carries a discretized notion of the FRP concept. This is likely also the reason why Sodium has adopted this name. With #52 this will no longer be suitable for Carboxyl.

**Alternatives**

Previously both Carboxyl and Sodium used `Behaviour`. There is also `Signal` as an alternative. Personally I like `Signal` better, but `Behaviour` appears to be more established.

**Comment by mitchmindtree** [comment]
+1, I was originally confused by point 1 the first time I checked out carboxyl :)

I also prefer the term `Signal` (imo the internal visualisation is perhaps a bit clearer). Disclaimer: my only previous experience with FRP is making a game with `Elm`.

**Comment by milibopp** [comment]
For what it's worth, Elm does not distinguish between Stream/Event and Cell/Behaviour/Signal at all. It just unifies both into a single type. But that unification is a discretely changing value, not a disjoint series of singular events, so I find it ok to use it for the continuous analogue, too. (And also because of the established analogous meaning in physics and engineering.)

I guess the main argument against "behaviour" is that it is OOP terminology for the verbs defined by a class.
