### ISSUE TITLE
Test algebraic laws of primitives using Quickcheck

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#55]
This would be really nice to have to test the current implementation as thoroughly as possible. Requires a couple of issues to be resolved:
- [x] Generate arbitrary streams and signals in a sensible manner.
- [ ] ~~Generate test functions, as the algebraic laws often hold for any function.~~
- [x] Test streams and signals for equality. (Fully implementing PartialEq or Eq is not feasible, but one can probe them for a while to see, whether they yield similar results.)
- [x] Within a transaction sampling a signal should always yield the same value.
- [x] Test that `Signal` and `Stream` are monoids, (applicative) functors and monads. (See push-pull paper for this.)
- [ ] ~~Specify and test in how far `SignalMut` and `Signal` are equivalent.~~
- [ ] ~~Specify and test the subset of algebraic properties implemented by `SignalMut`.~~

_Note: marked items have been implemented & merged._

**Comment by milibopp** [comment]
Let's start to specify the semantics that ought to be tested here. Much of this is taken/adapted from [Conal Elliott's paper on Push-Pull FRP](http://conal.net/papers/push-pull-frp/push-pull-frp.pdf). We assume a testable notion of equality denoted as `==`. Furthermore, trait bounds like `Send + Sync + Clone + 'static` are implied as required and omitted for better readability.

# Streams

## Monoid

_For reference: [Wikipedia: Monoid](https://en.wikipedia.org/wiki/Monoid)_

The streams of type `Stream<T>` should form a monoid under `Stream::merge` with `Stream::never()` being the identity. Thus, for arbitrary `a, b, c: Stream<T>` the following properties hold:
- left identity: `Stream::never().merge(&a) == a`,
- right identity: `a.merge(&Stream::never()) == a`,
- associativity: `a.merge(&b).merge(&c) == a.merge(&b.merge(&c))`.

While this certainly holds when all events are fired in separate transactions, there could be an issue with events from the same transaction.

## Functor

_For reference: [Wikipedia: Functor (type theory)](https://en.wikipedia.org/wiki/Map_%28higher-order_function%29)_

Streams form a functor under `Stream::map`, i.e.
- the identity function is preserved: `a.map(|x| x) == a`,
- it respects function composition: `a.map(f).map(g) == a.map(|x| g(f(x)))`.

Here, `f: Fn(T) -> U` and `g: Fn(U) -> V` if `a: T`.

## Monad

_For reference: [Wikipedia: Monad (functional programming)](https://en.wikipedia.org/wiki/Monad_%28functional_programming%29#Monad_laws)_

Streams in principle form a monad under a `bind` or `flat_map` operation defined as:

``` rust
fn bind<T, U, F: Fn(T) -> Stream<U>>(a: &Stream<T>, f: F) -> Stream<U> {
    a.map(f).switch()
}
```

(Question: Push-Pull FRP delays past event occurrences until the generation of the inner event. Is this necessary for the algebraic laws to hold? And how does this compare to the non-lazy transactional environment Carboxyl's working in?)

The neutral element is less trivial to construct in Carboxyl. In Push-Pull FRP it is modelled as a stream that fires exactly once in the infinite past. We cannot do this. However, maybe it is possible to mimick it somehow like this:

``` rust
fn return<T>(value: T) -> Stream<T> {
    let sink = Sink::new();
    let stream = sink.stream();
    sink.send(value); // Too early?
    stream
}
```

(We can't call it `return` because that's a keyword in Rust, but I wanted to use Haskell terms as a reference.)

The problem here is obviously, that the value will be sent before any consumers of the stream can listen to it. Somehow streams must be constructed in such a way, that `return(x).hold(y)` always samples as `x`. This may require some tweaks to the internals. (E.g. an event could hypothetically store its last occurence as an optional value.)

Nonetheless, for adequate implementations of `return` and `bind` the monad laws state that
- `return` acts as a neutral element:
  - `return(x).bind(f) == f(x)`,
  - `a.bind(return) == a`,
- `a.bind(f).bind(g) == a.bind(|x| f(x).bind(g)`.

The monad implies an applicative functor but this is not a particularly useful notion here (see Elliott paper).

# Signals

## Functor

Signals form a functor under unary lifts. So for `a: Signal<T>`, `f: Fn(T) -> U`, `g: Fn(U) -> V`
- `lift!(|x| x, &a) == a`,
- `lift!(|x| g(f(x)), &a) == lift!(g, &lift!(f, &a))`.

## Applicative functor

_For reference: [Haskell docs on Applicative](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base/Control-Applicative.html)_

To make signals an applicative we need a `pure` function, which in Carboxyl's API is the same as `Signal::new`, creating a signal with a constant value. Further we need a combining operator like this:

``` rust
fn cmb<A, B, F: Fn(A) -> B>(f: &Signal<F>, a: &Signal<A>) -> Signal<B> {
    lift!(|f, a| f(a), f, a)
}
```

_Note: A (small) technical problem here is that most functions in Rust are not `Clone`. This could be alleviated by wrapping it in an `Arc`. However, in the long-term this should be addressed by an upstream RFC, as this work-around introduces a performance penalty. For simplicity, we'll assume that closures are `Clone` here._

Now, the following laws must hold:
- identity: `cmb(&pure(|x| x), &a) == a`
- composition: `cmb(&cmb(&cmb(&pure(comp), &f), &g), &h) == cmb(&f, &cmb(&g, &h))` where `f`, `g`, `h` are signals of composable functions and `comp` denotes function composition.
- homomorphism: `cmb(&pure(f), &pure(x)) == pure(f(x))`
- interchange: `cmb(&f, &pure(x)) == cmb(&pure(|g| g(x)), &f)`

# Monad

Elliott mentions that signals also form a monad, but does not elaborate this. Presumably this works with similarly to streams using `switch` to construct the `bind` operation. Constructing `return` should be easier as it is simply `Signal::new`. This monad may imply the applicative above.

**Comment by aepsil0n** [comment]
There's some initial work on this branch: 00b5877
