### ISSUE TITLE
Properly implement a transaction system

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#6]
This is a plan to implement a transaction system to ensure that effects of events to not overlap inappropriately.
- [x] Step 1: Implement sequential transactions using a global lock. This ensures the semantics to be correct first. (see PR #13)
- [ ] Step 2: Use software transactional memory (STM) to achieve concurrent transactions. This is important for performance at some point, but may be quite a large implementation effort.

_Original post_

To provide stronger guarantees on how events are ordered, a transaction system should be implemented. This needs some research though.

**Comment by milibopp** [comment]
cc @the-real-blackh

Context: I've been hacking on this little FRP library in Rust (inspired by Sodium) for the last couple of days and am not quite sure how to deal with transactions. Apparently you implemented [this](https://github.com/SodiumFRP/sodium/blob/master/rust/sodium/transaction.rs) two years ago, so I thought maybe you could share your thoughts about this?

**Comment by the-real-blackh** [comment]
There's not a lot to say about this. I am not very good at Rust yet so I had a bit of trouble figuring the threading stuff out and never got very far with it. You can take the Java implementation as a specification for how it should work. A transaction is used to make updates atomic, and in Sodium I am currently using a single big mutex. This is a minimal implementation, and the technique may not work directly in Rust.

**Comment by milibopp** [comment]
Thanks for the quick feedback. So I had a look at the Java implementation. If I understand it correctly, there is always only one transaction running at the same time. I suppose a transaction is either creating a new stream/cell or firing an event.

What I'm doing at the moment, is using atomic ref-counting and explicit read/write locks for every node in the event graph. This is highly concurrent, but has the property that the effects of two independent events may arrive in a different order in different parts of the graph. You can explicitly fire events in a synchronous manner though to ensure their effects are ordered the same everywhere. Is this property problematic in practice?

The single big mutex concept should be transferrable to Rust, now that the synchronization primitives are stable. Using transactions for atomicity, I could probably use non-atomic ref-counting without locks for the pointers in the underlying graph structure.

**Comment by the-real-blackh** [comment]
The current implementation of Sodium has had almost no work done on performance, so you can treat it as a reference implementation. Obviously one big mutex throws concurrency out the window. It's good that you're working on performance, but note that it could be a lot of work. It might be worth writing a reference implementation first, then you can work on performance and you have something to test against.

What you're doing with a lock for each node is the right approach, but when they conflict you'll have to decide which transaction is logically first. If you use the method of STM (Software Transactional Memory) this will do it for you. This is a Haskell thing and you can read pretty simple papers about it by Simon Peyton Jones. Basically what it does is it locks things as it goes along, and when transaction A can't acquire a lock, it rewinds all the changes for transaction A and replays the transaction from the beginning. Perhaps it can be made more efficient than that, but there is zero risk of deadlock, which is the important thing.

I should add that Rust is one of the languages I really want for Sodium, so I'd be most grateful if you decided to contribute.

**Comment by milibopp** [comment]
Ok, I see that implementing this with STM is a bit of effort. I think I will follow your suggestion and use the global lock without avoid the internal locking for now. Using some sort of lock-based STM for better concurrency certainly makes sense as a future goal for this library, i.e. once anyone runs into performance issues with it. ^^

By deciding to contribute, do you mean to make this project part of Sodium, once it is more stable? My plan is anyway actually to develop and maintain it further, as I want to use it for game development in Rust. So in principle I am interested.

**Comment by the-real-blackh** [comment]
Yes, I'd definitely be pleased to make it part of Sodium. In my perfect world, FRP would be basic infrastructure like threading or networking. You would just write your code and it's done. Then what engine/platform/language you host it on doesn't matter.

**Comment by milibopp** [comment]
I've implemented the static mutex now. This was actually just a matter of [tapping into the Rust standard library](http://doc.rust-lang.org/nightly/std/sync/struct.StaticMutex.html) and encapsulating the entry points into the event graph. STM is going to be more complicated, but one thing at a time. I am still missing some pieces of the API, namely loops, stream switching and coalesce.

I have some practical questions regarding making this implementation part of Sodium. First of all, do you actually maintain all implementations across languages in the same repository? If so, what's your rationale behind that? I think I'd prefer keeping the repository separate, although a single place to track and discuss language-agnostic issues is generally a good idea.

Another question is about licensing: this project is currently under GPL 3.0+ (which is what I choose by default). Is that compatible with your plans?

**Comment by the-real-blackh** [comment]
Yes, I do maintain all languages in the same repository. No especially good reason, but I'm seeing it as a single project, but expressed in different languages. If there are major changes, I want to do them to all versions and tag together, etc. When I've finished writing the book I want to make some changes and do some nice packaging.

I have chosen a BSD licence because GPL prevents its use in proprietary software which is something I want to encourage. It's your work, so it's up to you. There's no reason why it can't be GPL on one language and BSD on the others.

If you choose GPL then you're promoting free software primarily. If you choose BSD you're promoting wide adoption primarily. I want FRP to become basic, common infrastructure. My view is that basic infrastructure should have a very liberal licence. FRP (or anything else attempting to become basic infrastructure) is no good to anyone if it remains in the fringes because some people can't use it. But, like I said, it's something you have to weigh up.

However, I need to say that for the reasons above, if you do choose GPL, then I will gladly take your code, but for the reasons I gave, I will eventually write a BSD-licensed version (when I can find the time) to replace it.

I hope that makes sense.

**Comment by milibopp** [comment]
Yes, that makes perfect sense. To be honest I'm a bit on the fence about licensing libraries as I would like to promote both free software and wide adoption and that's just impossible. There's still some middle ground such as LGPL. I'll think about it.

**Comment by the-real-blackh** [comment]
LGPL is certainly a good option, but there can be some technicalities, so it's worth checking that carefully. What LGPL gives you is that you prevent someone enhancing the library and keeping that version prioprietary. That would prevent, for example, someone making a super-efficient engine based significantly on your code then keeping it to themselves. I don't think that's much of a concern in practice, but you need to weigh that up.

Unless there was a significant reason why LGPL prevented wide adoption, I wouldn't bother re-writing it to get a BSD licence like I would with GPL which completely prevents use in proprietary software.

**Comment by milibopp** [comment]
Eventually I decided to migrate to LGPL. I think that if somebody were to avoid using the library because of the LGPL's remaining requirements, that that is actually a use I would generally object to. So from my point of view, that kind of non-adoption is not actually problematic. Even though it may be rare in practice, I do not see enough merit in lifting that restriction. Admittedly that is fairly subjective and highly depends on how you weigh certain factors.

**Comment by the-real-blackh** [comment]
Yes, I think LGPL is a good choice.

**Comment by milibopp** [comment]
Closing in favour of #14.
