### ISSUE TITLE
Does not compile on current rust git

### ISSUE THREAD

**Issue by ids1024** [aepsil0n/carboxyl#83]
Compilation fails due to the api change in commit 
rust-lang/rust@dfa4bca88932a9503d0600bfa7ca24e6950935e6.

The solution is to change lines like `let weak = src.downgrade();` to `let weak = Arc::downgrade(&src);`.

This should probably be changed when the next rust nightly is released. Or if possible it would be good to support both versions of rust, but I don't know rust well enough to know if that is possible.

**Comment by milibopp** [comment]
Thank you for letting me know!

I think the latter version should have worked before as well, since `src.downgrade()` is only sugar for `Arc::downgrade(&src)`.

**Comment by milibopp** [comment]
note: when stabilized, this finally also takes care of #47.
