### ISSUE TITLE
Marble support

### ISSUE THREAD

**Issue by milibopp** [aepsil0n/carboxyl#87]
See RxMarbles. Some API that allows easy creation of scheduled event sequences without explicitly spawning a thread and feeding a Sink. Maybe as a separate crate.

**Comment by milibopp** [comment]
Definitely out of scope for this crate. Might be a sensible idea for carboxyl-time though.

**Comment by DigitalFurnaceGames** [comment]
Hi can you remove me , I think you got the wrong github handle... Keep
getting notifications :)

**Comment by Moredread** [comment]
@DigitalFurnaceGames You have the project on your watchlist (https://github.com/aepsil0n/carboxyl/watchers) it seems, you can cancel notifications yourself at the top, either "unwatch" or "ignore".
